### ISSUE TITLE
PR Preview

### ISSUE THREAD

**Issue by a01sa01to** [saitamau-maximum/blog#11]
https://github.com/actions/deploy-pages

| Input | Required? | Default | Description|
|--|--|--|--|
| preview | false | "false" | Is this attempting to deploy a pull request as a GitHub Pages preview site? (NOTE: This feature is only in alpha currently and is not available to the public!) |

PR Preview できそう...？

**Comment by sor4chi** [comment]
blog.maximum.vc/<branch-name>/...でサブパスにデプロイみたいなのはgithub pagesならよく見るけどね

**Comment by a01sa01to** [comment]
全然見たことないな...

**Comment by a01sa01to** [comment]
#67
